# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ master, master2.0 ]
  pull_request:
    branches: [ master, master2.0 ]

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: action/setup-java@v2
       with:
        distribution: 'adopt'
        java-version: "11"
     - uses: subosito/flutter-action@v1
       with:
        channel: "master"
     - run: flutter pub get
     - run: flutter analyze
     - run: flutter test